# Generated by Django 2.2 on 2019-09-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20190906_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='html_content',
            field=models.TextField(default='asd'),
        ),
    ]
