# Generated by Django 2.2 on 2019-09-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_cards_html_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='html_content',
        ),
    ]
