# Generated by Django 2.2 on 2019-09-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_remove_cards_html_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('image', models.FileField(blank=True, default='hills.png', upload_to='')),
            ],
        ),
    ]
