# Generated by Django 2.2 on 2019-09-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='logo',
            field=models.CharField(default='logo', max_length=20),
        ),
    ]
