# Generated by Django 2.2 on 2019-09-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_website_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='background_image',
            field=models.FileField(blank=True, default='hills.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='website',
            name='image_service_1',
            field=models.FileField(blank=True, default='hills.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='website',
            name='image_service_2',
            field=models.FileField(blank=True, default='hills.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='website',
            name='link_1',
            field=models.CharField(default='link_1', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='link_2',
            field=models.CharField(default='link_2', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='link_3',
            field=models.CharField(default='link_3', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='text_service_1',
            field=models.CharField(default='text_service_1', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='text_service_2',
            field=models.CharField(default='text_service_2', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='title_service_1',
            field=models.CharField(default='title_service_1', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='title_service_2',
            field=models.CharField(default='title_service_2', max_length=20),
        ),
    ]
