# Generated by Django 2.2 on 2019-09-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20190909_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='logo',
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(default='Set Title', max_length=20),
        ),
    ]
