# Generated by Django 2.2 on 2019-09-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_auto_20190910_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='image',
        ),
    ]
