# Generated by Django 2.2 on 2019-09-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_remove_website_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='email',
            field=models.CharField(default='your@email.com', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='link_2_content',
            field=models.CharField(default='text_link_2', max_length=1000),
        ),
        migrations.AddField(
            model_name='website',
            name='link_2_tab_content_1',
            field=models.CharField(default='link_2_tab_content_1', max_length=1000),
        ),
        migrations.AddField(
            model_name='website',
            name='link_2_tab_content_2',
            field=models.CharField(default='link_2_tab_content_2', max_length=1000),
        ),
        migrations.AddField(
            model_name='website',
            name='link_2_tab_opt_1',
            field=models.CharField(default='title_service_2', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='link_2_tab_opt_2',
            field=models.CharField(default='title_service_2', max_length=20),
        ),
        migrations.AddField(
            model_name='website',
            name='link_2_title',
            field=models.CharField(default='Title', max_length=1000),
        ),
        migrations.AddField(
            model_name='website',
            name='parallax_image',
            field=models.FileField(blank=True, default='hills.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='website',
            name='phone',
            field=models.CharField(default='Your phone number', max_length=10),
        ),
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(default='set-title'),
        ),
        migrations.AlterField(
            model_name='website',
            name='text_service_1',
            field=models.CharField(default='text_service_1', max_length=1000),
        ),
        migrations.AlterField(
            model_name='website',
            name='text_service_2',
            field=models.CharField(default='text_service_2', max_length=1000),
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(default='Set_Title', max_length=20),
        ),
    ]
